server:
  port: 8081
  servlet:
    context-path: /crud
  error:
    include-message: always #获取异常信息
    include-exception: true #启用自定义异常面获取异常对象
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 3333
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false #禁用缓存
  mvc:
    format:
      date: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true #设置隐藏标签启用put方法
#    view:
#      prefix: /
#      suffix: .html
#    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper文件映射路径
